### ISSUE TITLE
Filetransfer change port

### ISSUE THREAD

**Issue by matteochretien** [mbentley/docker-teamspeak#24]
Hi, I would like to know how to change the file transfer port, I tried all the ways but nothing works with this teamspeak service

**Comment by mbentley** [comment]
Knowing what you tried would be helpful.  You should be able to follow the [README section here about updating the parameters](https://github.com/mbentley/docker-teamspeak#additional-parameters).

The quickstart guide specifically mentions that you need to pass both of these parameters if you're changing the port.  Since you're running TS in a container, you still want to use file transfer IP `0.0.0.0`.

```
• filetransfer_port (30033)
  TCP Port opened for file transfers. If you specify this parameter, you also need to specify the
  “filetransfer_ip” parameter!
  Default: The default file tranfer port is 30033.

• filetransfer_ip (0.0.0.0)
  IP on which the file transfers are bound to. If you specify this parameter, you also need to
  specify the “filetransfer_port” parameter!
  Default: File transfers are bound on any IP address.
```

**Comment by matteochretien** [comment]
Yes I tried that too but I always get the same mistake when I want to add an icon for example

**Comment by matteochretien** [comment]
Ok solved, my bad.
